export const siteconfig = {
    1: {
        config: {
            name: '',
            theme: '',
            about: '',
            hosts: [],
            logo:'',
            know_more: '',
            favicon: ''
        }
    },
    2: {
        config: {
            name: '',
            theme: '',
            about: 'W',
            hosts: [],
            logo:'',
            know_more: '',
            favicon: ''
        }
    }
}